# Generated by Django 5.1.2 on 2024-11-27 11:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_userprofile_college_userprofile_is_college_student_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menu",
            name="available",
        ),
        migrations.AddField(
            model_name="menu",
            name="ingredient_list",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="menu",
            name="rating",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1.0),
                    django.core.validators.MaxValueValidator(5.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="menu",
            name="ingredients",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="menus",
                through="api.MenuIngredient",
                to="api.ingredient",
            ),
        ),
    ]
