# Generated by Django 5.1.2 on 2024-11-29 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_menu_available_menu_ingredient_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(blank=-1, decimal_places=2, max_digits=10, null=True),
        ),
    ]
